"""Deployment dependency contract tests."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_server_requirements_include_challenge_engine_runtime() -> None:
    """The hosted v2 route imports NumPy through ``scripts.engine``."""
    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    normalized = {
        line.split("#", 1)[0].strip().lower()
        for line in requirements.splitlines()
        if line.split("#", 1)[0].strip()
    }
    assert any(
        requirement == "numpy"
        or requirement.startswith(("numpy=", "numpy<", "numpy>", "numpy!", "numpy~"))
        for requirement in normalized
    )


def test_production_deploy_uses_hashed_lock() -> None:
    """Render must install one reviewed Python 3.11 resolution."""
    render = (ROOT / "render.yaml").read_text(encoding="utf-8")
    lock = (ROOT / "requirements-production.txt").read_text(encoding="utf-8")

    assert "pip install --require-hashes -r requirements-production.txt" in render
    assert lock.count("--hash=sha256:") >= 20
    assert "autogenerated by pip-compile with Python 3.11" in lock


def test_distribution_backend_is_exactly_pinned() -> None:
    """Independent builders must resolve the same packaging backend."""
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert 'requires = ["setuptools==81.0.0"]' in pyproject


def test_mcp_container_uses_hashed_lock() -> None:
    """The public MCP image must not resolve dependencies during deployment."""
    dockerfile = (ROOT / "Dockerfile").read_text(encoding="utf-8")
    lock = (ROOT / "requirements-mcp-lock.txt").read_text(encoding="utf-8")
    requirements = (ROOT / "requirements-mcp.txt").read_text(encoding="utf-8")
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")

    assert "--require-hashes -r requirements-mcp-lock.txt" in dockerfile
    assert "pip install --no-cache-dir --no-deps ." in dockerfile
    assert 'ENTRYPOINT ["/usr/local/bin/mettle-mcp-entrypoint"]' in dockerfile
    assert '"mcp>=2.0,<3"' in pyproject
    assert "mcp>=2.0,<3" in requirements
    assert "mcp==2.0.0" in lock
    assert lock.count("--hash=sha256:") >= 10


def test_mcp_container_context_is_allowlisted_and_transport_is_validated() -> None:
    """Unrelated working files cannot enter the image, and invalid modes fail."""
    dockerignore = (ROOT / ".dockerignore").read_text(encoding="utf-8")
    assert dockerignore.splitlines()[2] == "**"
    assert "!mettle/**" in dockerignore
    assert "!deploy/mcp/entrypoint.sh" in dockerignore
    assert "!static/" not in dockerignore

    entrypoint = ROOT / "deploy/mcp/entrypoint.sh"
    result = subprocess.run(
        ["sh", str(entrypoint)],
        env={**os.environ, "METTLE_MCP_TRANSPORT": "invalid"},
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 64
    assert result.stderr == "Unsupported METTLE_MCP_TRANSPORT: invalid\n"


def test_render_auto_deploy_is_the_only_main_deployment_authority() -> None:
    """A main commit must not trigger both Render and a deploy-hook workflow."""
    render = (ROOT / "render.yaml").read_text(encoding="utf-8")

    assert "autoDeploy: true" in render
    assert not (ROOT / ".github/workflows/deploy.yml").exists()
